### ISSUE TITLE
Unable to install Allscan on new install of Allstarlink ASL3

### ISSUE THREAD

**Issue by bigbill2105** [davidgsd/AllScan#12]
I am unable to install Allscan on new install of Allstarlink ASL3. When trying to run sudo ./AllScanInstallUpdate.php I get the following error.
sudo: unable to execute ./AllScanInstallUpdate.php: No such file or directory

Here is what I did to try to install Allscan:

kj5gfx@node62392:~ $ sudo https://raw.githubusercontent.com/davidgsd/AllScan/main/AllScanInstallUpdate.php
sudo: https://raw.githubusercontent.com/davidgsd/AllScan/main/AllScanInstallUpdate.php: command not found
kj5gfx@node62392:~ $ sudo wget 'https://raw.githubusercontent.com/davidgsd/AllScan/main/AllScanInstallUpdate.php'
--2024-08-23 12:02:31--  https://raw.githubusercontent.com/davidgsd/AllScan/main/AllScanInstallUpdate.php
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8902 (8.7K) [text/plain]
Saving to: ‘AllScanInstallUpdate.php’

AllScanInstallUpdate.php                            100%[==================================================================================================================>]   8.69K  --.-KB/s    in 0.005s  

2024-08-23 12:02:31 (1.83 MB/s) - ‘AllScanInstallUpdate.php’ saved [8902/8902]

kj5gfx@node62392:~ $ ls -a
.  ..  AllScanInstallUpdate.php  .bash_history  .bash_logout  .bashrc  .profile  .sudo_as_admin_successful
kj5gfx@node62392:~ $ sudo chmod 755 AllScanInstallUpdate.php
kj5gfx@node62392:~ $ sudo ./AllScanInstallUpdate.php
sudo: unable to execute ./AllScanInstallUpdate.php: No such file or directory
kj5gfx@node62392:~ $ ls -a
.  ..  AllScanInstallUpdate.php  .bash_history  .bash_logout  .bashrc  .profile  .sudo_as_admin_successful

**Comment by davidgsd** [comment]
Try running 'sudo apt install php'.

**Comment by bigbill2105** [comment]
Thank you! That did the trick.

Bill-KJ5GFX
