### ISSUE TITLE
favsUtils.php not found error

### ISSUE THREAD

**Issue by gulbalee** [davidgsd/AllScan#13]
I get the following error when allscan is installed. The page doesnt open.

`[Wed Oct 16 02:10:09.146523 2024] [php:error] [pid 87034:tid 87034] [client 127.0.0.1:39888] PHP Fatal error:  Uncaught Error: Failed opening required 'favsUtils.php' (include_path='.:/usr/share/php') in /var/www/html/allscan/include/common.php:9\nStack trace:\n#0 /var/www/html/allscan/index.php(4): require_once()\n#1 {main}\n  thrown in /var/www/html/allscan/include/common.php on line 9
`

I commented 'require favutils.php' line as allscan/include folder didnt have favutils.php neither could i see it in github. The new user creation page showed up once the line was commented, however after creating new user when login page showed up, I again got an error

`[Wed Oct 16 02:18:05.700325 2024] [php:warn] [pid 87472:tid 87472] [client 127.0.0.1:55416] PHP Warning:  Undefined variable $newUser in /var/www/html/allscan/user/index.php on line 222, referer: http://XXXXX/allscan/user/
[Wed Oct 16 02:18:20.384174 2024] [php:error] [pid 87474:tid 87474] [client 59.103.27.26:2915] PHP Fatal error:  Uncaught Error: Call to undefined function findFavsFiles() in /var/www/html/allscan/index.php:63\nStack trace:\n#0 {main}\n  thrown in /var/www/html/allscan/index.php on line 63,`

**Comment by davidgsd** [comment]
Hi, thanks for opening a bug report on this. There was a new file that had not been checked in, but has now been added here.  You should now be able to run in the installer again and the new file will be correctly downloaded.
