### ISSUE TITLE
not seeing call sign or location on top of page or favourites

### ISSUE THREAD

**Issue by VO1DNK** [davidgsd/AllScan#14]
hey  just setup the allscan i can log into page connect to node but not seeing my call sign or location on top of page also wondering how to place my favorites on page thanks

**Comment by davidgsd** [comment]
You can set your call sign and location on the Cfgs link.  Favorites can be added with the Add Favorites button.  If you do not have a favorites file AllScan should create one for you. If you're not seeing that please send an email to david @ allscan . info with a screenshot of what you're seeing. Thanks
