### ISSUE TITLE
Echolink nodes

### ISSUE THREAD

**Issue by jturning** [davidgsd/AllScan#2]
If you change line 135 to:

`				if(preg_match('/[0-9]{4,7}/', $c, $m) == 1)`

It will support Echolink 7 digit node numbers. But then the stat function errors out on the first Echolink node. I'm not too PHP savvy, so is there a way to have it continue processing entries. As a work around I moved all my Echolink entries to the bottom. Would be nice to recognize 7 digit nodes are Echolink and label as such and continue with grabbing stats for Allstar nodes instead of flagging as errors. And thanks for a great project to improve Allstarlink.

![Screenshot from 2022-12-23 12-53-58](https://user-images.githubusercontent.com/37452682/209400410-6d987c04-3532-45e4-916f-e7002ea9d9ab.png)

**Comment by davidgsd** [comment]
Thanks for submitting the first AllScan issue : )  This has been fixed in v0.37.
**v0.37 2022-12-23**<br>
Support 7-digit (EchoLink) node numbers when reading in favorites.ini. Fix issue where stats request scanning would stop once it reached an EchoLink node number in the Favorites Table.
