### ISSUE TITLE
No where to be found after install

### ISSUE THREAD

**Issue by wrhowell** [davidgsd/AllScan#5]
I read your information all the way thru on the subject of installing allscan. I have five or more servers running ASL. When doing a version check from the asl-menu it shows "Asterisk GIT Version 004b9dd built by root @ stretch-64 on a x86_64 running Linux ---"
(not sure if that helps or not)....

Anyways, after doing the ./AllScanInstallUpdate.php and watching it to the install and then showing complete, when I enter the ipaddress/allscan I get a 404 page, I then went looking into the /var/www/html and there's no allscan listed.

Is the version of ASL too old for allscan or should I be looking for some other issue?

KI5PHN

**Comment by davidgsd** [comment]
Please copy and paste here all output messages shown on your SSH terminal when you run the install/update script.

**Comment by wrhowell** [comment]
I did a complete removal of that asl and did a Debian, then ASL install and now I have allScan up and running.

Question is, I've disabled the ability to pull the information from allstarlink.org in the file /var/www/html/allmon2/astdb.php & in the file /var/www/html/supermon/astdb.php  and then modified the astdb.txt under the /var/www/html/supermon/astdb.txt  directory & also with in the /var/log//asterisk/astdb.txt.... I put my own node info in these two files so that I could see how well it worked with my other non-asl nodes. The problem is when I run AllScan the "Connection Status show the proper info about the node, but the "Favorites" display info
![allscanpic](https://github.com/davidgsd/AllScan/assets/36932685/882c6e99-88e3-423d-9eed-76a8be822455)
 is way off... Where is "Favorites pulling this information from other than favorites within the supermon directory?
 
 Thank you

Ki5PHN

**Comment by davidgsd** [comment]
When displaying the Favorites table AllScan reads the node Call sign, Description and Location from astdb.txt if the node number exists there, otherwise will use the data in the favorites.txt file.  If you are seeing some kind of issue ie. believe this data is not being displayed correctly for any node #, please be more specific about what node #s, and what data you expected to see and what was actually shown.

**Comment by wrhowell** [comment]
Under the  "Favorites" section in the prior post photo --  line1 shows: Node: 40701 (which is correct)| Name: KN6GNG NE Texas HUB NE Texas, USA (the "KN6GNG" should NOT be there)| DESC: - (not totally sure what should be listed there)| Location: Downey California (should say Canton, Texas) ....

Line 2: has right node number, has "W8CAN"  and shouldn't, under DESC has 446.675 and shouldn't, and Location shows a place in Ohio when it too should be Canton, Texas....

Line 3: right node number, KC2IDB shouldn't be there, and location is NJ when it should be Kaufman, Texas.

What I'm seeing happen is this,  I have changed the location in /var/www/html/supermon/astdb.php from allstarlink.org to a fake location, so when I ran ./astdb.php it came back with several retry attempts as it should then gave up. Then I removed all the info within the /var/www/html/supermon/astdb.txt and  /var/www/html/allscan/astdb.txt and inserted the info I wanted it to display. But, when I load the allscan web page it is replacing  /var/www/html/allscan/astdb.txt  with data pulled from allstarlink. I even have changed the /var/www/html/allmon2/astdb.php and made it the same as the supermon astdb.php and cleaned the file (astdb.txt) out under /var/log/asterisk/astdb.txt and inserted the same information just like the one in supermon's astdb.txt.... So where/how is your allscan getting the info from allstarlink if it only uses what is within the allmon2/supermon astdb.txt? Allscan is pulling both my info and the info from allstarlink. That call sign in line one is what allstarlink shows for that node number of 40700, plus the infor for 40701 and same with 40702, and at the same time it's also pulling my information from one of the astdb.txt files.... So where within your AllScan does the code exist that runs the astdb.php to get the allstarlink.org node number information? What am I missing and/or not seeing, please?

KI5PHN

**Comment by davidgsd** [comment]
AllScan is designed for use with ASL not GMRS. What you are describing is not standard use of the ASL DB. I am happy to help with ASL issues but what you're doing is not a standard ham radio or AllStar use case. For non-ham radio applications I could do custom development on a consulting basis but that would not be free. Contact me at david @ allscan . info if you wanted to pursue custom development for your application. You might also want to try Supermon, it may do what you want more easily. Thanks

**Comment by wrhowell** [comment]
Thanks, Allmon2 and Supermon work as designed for both Amateur and GMRS... and without issues... as does the asterisk software. I were thinking maybe it would bring you some benefits if I managed to get it working for both but I guess I was wrong in my thinking.

I appreciate the offer. I'll keep working at it and figure it out or not.

Thanks again,
KI5PHN

**Comment by davidgsd** [comment]
The main benefit of AllScan over AllMon or Supermon is its use of the ASL stats API, and as such it is inherently an ASL-specific app. Thus I wouldn't see a major benefit of using it on GMRS, but may be open to code contributions to facilitate it working on other networks if this could provide a significant value add beyond what's available from other existing apps. Thanks

**Comment by wrhowell** [comment]
"Thus I wouldn't see a major benefit of using it on GMRS, but may be open to code contributions to facilitate it working on other networks if this could provide a significant value add beyond what's available from other existing apps. "

I'll contact you by email later today and we can converse on this subject there.

William KI5PHN
