### ISSUE TITLE
AllScanInstallUpdate.php does not run on x64 systems

### ISSUE THREAD

**Issue by omaudio** [davidgsd/AllScan#9]
Hi David- 
Appears there may be an issue running update on x64. I get file not found after changing permissions step in the install. (new Pi4 and latest fully updated OS and ASL 3 image/system). The file is there and permissions are correct. Researching online suggests x64 issue as possibility.
Clifford

**Comment by Allan-N** [comment]
Do the following commands, exec'd before `./AllScanInstallUpdate.php` help :
```
apt update
apt install -y php php-curl php-sqlite3
```

**Comment by davidgsd** [comment]
Hi Clifford, any update after trying the commands Allan suggested above?  If not can you post the complete log of output messages from the install script and a "ls -la" of the directory in question? Thanks, David

**Comment by davidgsd** [comment]
Closing issue as it appears from other messages on issue #10 that everything is working now, If not please post more details on issue. Thanks
